perl:
  - "5.18"
  - "5.8"
install: "make test-deps"
script: "make test"
notifications:
  email:
    - wakaba@suikawiki.org
  irc:
    channels:
      - "irc.suikawiki.org#mechanize"
    use_notice: true
